# Generated by Django 3.0.8 on 2020-08-10 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix')),
            ],
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('souscriptionDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de souscription')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='adresse')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='users',
            field=models.ManyToManyField(through='meeting.Souscription', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs souscrits'),
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('description', models.TextField()),
                ('secret', models.CharField(max_length=255, verbose_name='Code secret')),
                ('beginDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de fin')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Initiateur')),
                ('participants', models.ManyToManyField(related_name='_conference_participants_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
