# Generated by Django 3.0.8 on 2020-08-11 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0003_auto_20200811_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Initiateur'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='participants',
            field=models.ManyToManyField(related_name='conferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
